# docker-compose.yml

services:
  tiktokar-bot:
    build: .
    container_name: tiktokar-bot-container
    env_file:
      - .env
    volumes:
      - media_temp:/app/temp
    restart: unless-stopped

volumes:
  media_temp: